### PR TITLE
Add Analytics

### PR DESCRIPTION
**Pull request by fitzthum**
Setup Google analytics on the website. Before we start a big push on website content, let's setup analytics so we know if anyone is looking at the site and which pages they are most interested in. 

Unfortunately we don't have a great way to hook google analytics into our github organization. This property is linked to my google account, but it can be shared with anyone else's google account. Lmk if there is a better way to handle this.

### CODE REVIEW

**Comment by fitzthum** [comment]
@mkulke @surajssd @confidential-containers/tsc 

Can someone take a look at this.

I am anticipating a big push on the website but maybe we need to find some additional maintainers.

**Comment by bpradipt** [comment]
> @mkulke @surajssd @confidential-containers/tsc
> 
> Can someone take a look at this.
> 
> I am anticipating a big push on the website but maybe we need to find some additional maintainers.

True, and also the website need some updates.. Any helping hands will be awesome

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by bpradipt** [comment]
> Unfortunately we don't have a great way to hook google analytics into our github organization. This property is linked to my google account, but it can be shared with anyone else's google account. Lmk if there is a better way to handle this.

Is there something that CNCF provides ?

**Review by surajssd — APPROVED** [review]

**Comment by fitzthum** [comment]
> Is there something that CNCF provides ?

I didn't see anything [here](https://contribute.cncf.io/resources/project-services/) but I can ask around.

Also I'm not totally confident this PR actually worked. It might need some time.

**Pull request merged**
