### PR TITLE
Update Docs

### PR DESCRIPTION
**Pull request by fitzthum**
Lots of changes with the docs; ~~just a draft for now.~~

### CODE REVIEW

**Comment by portersrc** [comment]
I went through the trust model docs, and those sections look great.

**Comment by fitzthum** [comment]
> with this change the Instructions for Peerpods has been removed. Was this intentionally? at least for Azure this was where the end-user focussed documentation was being maintained.

Generally I want to try to converge the peer pods directions with the bare metal directions, but I didn't mean to delete the Azure docs.

One place this could potentially live in the new layout is getting started -> pre-requisites -> hardware -> cloud -> azure
Is that too deeply nested? 

Also is it valid separate out this stuff as pre-requisites? I'd like it if we just had setup steps and then people moved onto generic steps to install the operator and runt he workload. It seems like that can probably work if we add a `cloud` tab to the operator setup step. wdyt? I understand if you want to keep the full end-to-end instructions in place somewhere. Maybe we could add an examples section?

**Comment by mkulke** [comment]
> One place this could potentially live in the new layout is getting started -> pre-requisites -> hardware -> cloud -> azure Is that too deeply nested?
> 
> Also is it valid separate out this stuff as pre-requisites? I'd like it if we just had setup steps and then people moved onto generic steps to install the operator and runt he workload. It seems like that can probably work if we add a `cloud` tab to the operator setup step. wdyt? I understand if you want to keep the full end-to-end instructions in place somewhere. Maybe we could add an examples section?

putting it under pre-requisites feels a bit odd. Can we put it below getting started / installation / Azure? We could have similar instructions for other CSPs as siblings, or possibly a non-TEE qemu entry that covers everything from local k8s cluster installation to coco runtimeclass (in a similar copy/paste fashion as the azure docs). the installation page could still keep the more generic, brief installation instructions.

**Comment by fitzthum** [comment]
@mkulke yeah seems tricky for the installation page that I currently have to capture everything in tab boxes. It can accommodate switching to different CRDs and CRs but the earlier steps where you download CAA don't really fit.

For this PR can I just move the azure page as-is to a new top-level example section and then we think about how to handle peer pods? I don't really know how peer pods installation works.

I suspect we probably want to add a cloud section to the installation section. Do we split it into two pages: cloud, and bare-metal (that mutually exclusive)? Do we add another step for peer pods that is optional (before installation but after per-requisites)?

I think some of the Azure stuff can go in pre-requisites; everything before installing CAA? wdyt?

**Comment by mkulke** [comment]
> @mkulke yeah seems tricky for the installation page that I currently have to capture everything in tab boxes. It can accommodate switching to different CRDs and CRs but the earlier steps where you download CAA don't really fit.
>

what I mean is to move 

> For this PR can I just move the azure page as-is to a new top-level example section and then we think about how to handle peer pods? I don't really know how peer pods installation works.
> 
> I suspect we probably want to add a cloud section to the installation section. Do we split it into two pages: cloud, and bare-metal (that mutually exclusive)? Do we add another step for peer pods that is optional (before installation but after per-requisites)?
> 
> I think some of the Azure stuff can go in pre-requisites; everything before installing CAA? wdyt?

What I would suggest is to move the `azure` folder as-is from `cloud-api-adaptor` into the `getting_started/installation` folder, it'll appear as a subpage there. next to subpages for bare metal, non-tee, aws, ...

I would not recommend chopping up the documentation in generic and specific steps and leaving it to reader to puzzle it together (even if that means some redundancy)

**Comment by fitzthum** [comment]
I feel pretty strongly about making the docs as generic as possible. Not doing so with the existing docs has created nothing but problems. With siloed docs maintainers only focus on their own sections which decreases quality and everybody ends up doing more work because individual sections are longer and more complex. This gets worse as we add more platforms and features. Let's not underestimate how painful redundancy can be. We've really struggled with this in the github docs.

More fundamentally, we've struggled with making the project generic since day 1. If we keep the docs separate we enable ourselves to continue not really worrying about convergence which I think is a big mistake. Putting everything together is a good way to push in the other direction. It will definitely show us where we need to do some more work. 

That said, I understand that you guys have put time into the az doc in particular and that it is proven to work. That's why I suggest keeping it around in examples or some other place (even though that does also create some redundancy). I don't think it will be too puzzling for users to figure out the prerequisite steps. If it is then we probably need to make the project itself simpler. I don't want to put the az doc under the installation section as-is. It would be odd to have a pre-requisites and installation section next to another doc that also contains those steps.

**Comment by mkulke** [comment]
> I feel pretty strongly about making the docs as generic as possible. Not doing so with the existing docs has created nothing but problems. With siloed docs maintainers only focus on their own sections which decreases quality and everybody ends up doing more work because individual sections are longer and more complex. This gets worse as we add more platforms and features. Let's not underestimate how painful redundancy can be. We've really struggled with this in the github docs.

I see. in this case I wouldn't know how to meaningfully split the existing docs. there is ~1 line in the azure/peerpod doc that is generic (kustomize-apply the operator). If the website is not the place for this kind of setup guide, I'd suggest moving it back to the caa repo, I think the other cloud's documentation has been maintained there (the content on the website is mostly a stale copy from some point in time).

wdyt @bpradipt @stevenhorsman? (should peerpods guides stay in the caa repo)

**Comment by stevenhorsman** [comment]
> wdyt @bpradipt @stevenhorsman? (should peerpods guides stay in the caa repo)

I think we should have a single place for this documentation. Where there is is a good question. I understand the idea of having the user facing docs in the confidential containers website, as long as it's kept up-to-date, but if the website is supposed to be generic and only have things that apply to enclave-cc, bare-metal and peer-pods (I might have misunderstood this point, but I'm worried will mean it doesn't work well enough for anyone?) then I think we'll have to keep them in the CAA repo if the alternative is to not have any specific docs?

**Comment by fitzthum** [comment]
The website should absolutely have peer pods information on it. The idea is not to only have information that is common to all. It's to not duplicate information that is common to all. 

For instance, we can add a tab on the installation page that installs the peer pods overlay. Let's also add a note at the top of the installation guide that points out that there are tabs in case people miss them and that tells people to look at the pre-requisites. We can also explain the different deployment types a little more clearly at the very beginning.

Currently I have cloud under hw pre-requisites, which doesn't make much sense, so I can move that next to hw and sw. I think that's a reasonable place to add the cloud provisioning steps. Then we just need to find a place to put the installation of the CAA adaptor itself. Maybe under installation. I don't quite have the picture but this is the sort of thing I envision.

I was planning to do peer pods as a follow-up, but I want to make sure we're on the same page here. If you guys think that it's too hard to disentangle the peer pods installation into individual steps, we can think about some alternatives, but that seems like a red flag to me.

One thing to think about is that the CNCF has fairly specific requirements regarding vendor neutrality on project websites and elsewhere. I don't think we're violating any of them, but making things more generic steers us in the right direction.

**Comment by stevenhorsman** [comment]
> The website should absolutely have peer pods information on it. The idea is not to only have information that is common to all. It's to not duplicate information that is common to all and to structure all the flows we have floating around in the project into discrete, digestible, and interlinked pieces.
> 
> For instance, we can add a tab on the installation page that installs the peer pods overlay. Let's also add a note at the top of the installation guide that points out that there are tabs in case people miss them and that tells people to look at the pre-requisites. We can also explain the different deployment types a little more clearly at the very beginning.

Ok cool - it sounds like I misunderstood what had been discussed. That sounds good, but like it might be a bit tricky to do, but we could do something like have the peer pods ccruntime within the general operator section and I guess trying to jump out into peer pods specific page to discuss the specific set-up of different cloud-providers (which I guess could be in the tabbed format again).

**Comment by bpradipt** [comment]
When I see the preview, the ordering is as shown below
image

Since "Getting Started" is about installation only, I think a better ordering is after "Use cases".
May be you can merge "Getting Started"  and "Examples" into one section and rename it to "Deployment Examples" or "Deployment Scenarios" or "Tasks" etc.. and then have pages for different setup mechanisms (Kind/Kubeadm/AKS/EKS etc with and without peer-pods). Under that there could also be pages for sealed secrets, signed images etc. 

And in subsequently PRs, we can introduce the tabs for the deployment examples in different environments.

**Review by mkulke — APPROVED** [review]

**Comment by fitzthum** [comment]
> Since "Getting Started" is about installation only, I think a better ordering is after "Use cases".
May be you can merge "Getting Started" and "Examples" into one section and rename it to "Deployment Examples" or "Deployment Scenarios" or "Tasks" etc.. and then have pages for different setup mechanisms (Kind/Kubeadm/AKS/EKS etc with and without peer-pods). Under that there could also be pages for sealed secrets, signed images et

Here's how I see the different sections.

- Getting started: installation of CoCo only. gets users from zero to running an unsigned, unencrypted confidential container
- Features: Additional functionality that can be used on top of a basic installation, usually depending on attestation
- Examples: miscellaneous snippets of specific deployments of varying scope (which may or may not include installation). for example: using a couple of features together, using a feature with a particular workload, etc. Instructions for a lot of the demos we've seen could go here.
- Use cases: high level look at how to use coco with various types of applications.

I don't have the use cases section totally figured out. I am thinking it would be pretty high-level, with references to specific features and examples, but without specific directions. @bpradipt does that fit with what you've been doing with use cases or should the scope be a bit different?

**Comment by bpradipt** [comment]
> Here's how I see the different sections.
> 
> * Getting started: installation of CoCo only. gets users from zero to running an unsigned, unencrypted confidential container
> * Features: Additional functionality that can be used on top of a basic installation, usually depending on attestation
> * Examples: miscellaneous snippets of specific deployments of varying scope (which may or may not include installation). for example: using a couple of features together, using a feature with a particular workload, etc. Instructions for a lot of the demos we've seen could go here.

Where do you plan to add the Concepts, Architecture etc pieces ?

> * Use cases: high level look at how to use coco with various types of applications.
> 
> I don't have the use cases section totally figured out. I am thinking it would be pretty high-level, with references to specific features and examples, but without specific directions. @bpradipt does that fit with what you've been doing with use cases or should the scope be a bit different?

This is a good start, followed by any specific implementation details under examples or blogs.

**Comment by fitzthum** [comment]
> Where do you plan to add the Concepts, Architecture etc pieces ?

I forgot to put the architecture section on that list. That will be a top-level section containing general conceptual and design information including the design overview added in this PR and the trust model.

**Comment by fitzthum** [comment]
Ok, I am going to merge this. We will continue to iterate on it, but this is a good start and we need the architecture docs up somewhere for our incubation proposal. I will create some issues with next steps. I have checked the commit history in this repo and we're not removing anything that was website-exclusive.

**Pull request merged**
