### PR TITLE
favicon: Add icons

### PR DESCRIPTION
**Pull request by surajssd**

### CODE REVIEW

**Comment by surajssd** [comment]
Here one can see if the favicon shows up in all the browsers: https://realfavicongenerator.net/favicon_checker?protocol=https&site=deploy-preview-14--frolicking-manatee-96c0c8.netlify.app%2F

**Comment by surajssd** [comment]
In my manual testing the logo shows up on Chrome, Edge and Safari on MacOSX and Safari on iOS.

**Comment by surajssd** [comment]
This PR is ready for review.

**Review by fitzthum — APPROVED** [review]
LGTM

**Pull request merged**
