### PR TITLE
blog: add article about coco on non-tee

### PR DESCRIPTION
**Pull request by wainersm**
Title: Confidential Containers without confidential hardware
---

@stevenhorsman and I wrote this to be published on Red Hat's blog as an updated version of a previous blog. But I was talking with @ariel-adam this morning about publishing it here instead, which makes more sense as the content is 100% CoCo upstream. Moreover, it can sum-up on the efforts to promote the project to incubation because one strong requirement seems to be the capacity of users to run/experiment on a standard workstation, and this content explains how they can deploy and run CoCo (demo) on their laptops with non-TEE hardware.

Because it was targeted to Red Hat's blog readers, hence beginners to CoCo, there is an introduction that might not make much sense here, even though I was too lazy to remove it (and I liked the intro text...).

Cc @fitzthum

### CODE REVIEW

**Comment by wainersm** [comment]
ah, I could not make the website built locally with docker compose as explained on the CONTRIBUTING.md. Let's see on CI the errors (if any) on the text.

The docker compose error (same error if I ran from `main` without my changes):
```
$ docker compose up
WARN[0000] /home/wmoschet/src/github.com/confidential-containers/confidentialcontainers.org/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 1/0
 ✔ Container confidentialcontainersorg-site-1  Created                                                                                       0.0s 
Attaching to site-1
site-1  | Start building sites … 
site-1  | hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended linux/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=hugoguru
site-1  | WARN 2024/12/04 01:17:23 Config parameter '.params.ui.footer_about_disable' is DEPRECATED, use '.params.ui.footer_about_enable' instead.
site-1  | ERROR 2024/12/04 01:17:23 render of "page" failed: "/tmp/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.10.0/layouts/blog/baseof.html:17:15": execute of template failed: template: blog/single.html:17:15: executing "blog/single.html" at <partial "page-meta-links.html" .>: error calling partial: "/tmp/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.10.0/layouts/partials/page-meta-links.html:5:36": execute of template failed: template: partials/page-meta-links.html:5:36: executing "partials/page-meta-links.html" at <hugo>: can't evaluate field WorkingDir in type interface {}
site-1  | ERROR 2024/12/04 01:17:23 render of "page" failed: "/tmp/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.10.0/layouts/blog/baseof.html:17:15": execute of template failed: template: blog/single.html:17:15: executing "blog/single.html" at <partial "page-meta-links.html" .>: error calling partial: "/tmp/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.10.0/layouts/partials/page-meta-links.html:5:36": execute of template failed: template: partials/page-meta-links.html:5:36: executing "partials/page-meta-links.html" at <hugo>: can't evaluate field WorkingDir in type interface {}
site-1  | ERROR 2024/12/04 01:17:23 render of "page" failed: "/tmp/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.10.0/layouts/blog/baseof.html:17:15": execute of template failed: template: blog/single.html:17:15: executing "blog/single.html" at <partial "page-meta-links.html" .>: error calling partial: "/tmp/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.10.0/layouts/partials/page-meta-links.html:5:36": execute of template failed: template: partials/page-meta-links.html:5:36: executing "partials/page-meta-links.html" at <hugo>: can't evaluate field WorkingDir in type interface {}
site-1  | ERROR 2024/12/04 01:17:23 render of "page" failed: "/tmp/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.10.0/layouts/blog/baseof.html:17:15": execute of template failed: template: blog/single.html:17:15: executing "blog/single.html" at <partial "page-meta-links.html" .>: error calling partial: "/tmp/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.10.0/layouts/partials/page-meta-links.html:5:36": execute of template failed: template: partials/page-meta-links.html:5:36: executing "partials/page-meta-links.html" at <hugo>: can't evaluate field WorkingDir in type interface {}
site-1  | Built in 1880 ms
site-1  | Error: Error building site: failed to render pages: render of "page" failed: "/tmp/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.10.0/layouts/blog/baseof.html:17:15": execute of template failed: template: blog/single.html:17:15: executing "blog/single.html" at <partial "page-meta-links.html" .>: error calling partial: "/tmp/modules/filecache/modules/pkg/mod/github.com/google/docsy@v0.10.0/layouts/partials/page-meta-links.html:5:36": execute of template failed: template: partials/page-meta-links.html:5:36: executing "partials/page-meta-links.html" at <hugo>: can't evaluate field WorkingDir in type interface {}
site-1 exited with code 255
```

**Comment by wainersm** [comment]
I will send a version to fix the linter complains:

```
{"message": "[Vale.Terms] Use 'containerd' instead of 'Containerd'.", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 11, "column": 300}}}, "severity": "ERROR"}
  {"message": "[Vale.Spelling] Did you really mean 'vCPUs'?", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 39, "column": 78}}}, "severity": "ERROR"}
  {"message": "[Vale.Spelling] Did you really mean 'kubeadm'?", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 44, "column": 206}}}, "severity": "ERROR"}
  {"message": "[Vale.Terms] Use 'containerd' instead of 'Containerd'.", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 45, "column": 5}}}, "severity": "ERROR"}
  {"message": "[Vale.Terms] Use 'containerd' instead of 'Containerd'.", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 45, "column": 202}}}, "severity": "ERROR"}
  {"message": "[Vale.Spelling] Did you really mean 'kubeadm'?", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 46, "column": 170}}}, "severity": "ERROR"}
  {"message": "[Vale.Spelling] Did you really mean 'ccruntime'?", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 83, "column": 5}}}, "severity": "ERROR"}
  {"message": "[Vale.Spelling] Did you really mean 'ccruntime'?", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 86, "column": 31}}}, "severity": "ERROR"}
  {"message": "[Vale.Spelling] Did you really mean 'busybox'?", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 114, "column": 82}}}, "severity": "ERROR"}
  {"message": "[Vale.Spelling] Did you really mean 'nodeport'?", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 265, "column": 111}}}, "severity": "ERROR"}
  {"message": "[Vale.Spelling] Did you really mean 'oras'?", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 292, "column": 235}}}, "severity": "ERROR"}
  {"message": "[Vale.Spelling] Did you really mean 'unencrypt'?", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 332, "column": 107}}}, "severity": "ERROR"}
  {"message": "[Vale.Spelling] Did you really mean 'wget'?", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 366, "column": 117}}}, "severity": "ERROR"}
  {"message": "[Vale.Terms] Use 'Rego' instead of 'rego'.", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 395, "column": 325}}}, "severity": "ERROR"}
  {"message": "[Vale.Terms] Use 'Rego' instead of 'rego'.", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 407, "column": 93}}}, "severity": "ERROR"}
  {"message": "[Vale.Terms] Use 'Rego' instead of 'rego'.", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 409, "column": 28}}}, "severity": "ERROR"}
  {"message": "[Vale.Spelling] Did you really mean 'respin'?", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 409, "column": 57}}}, "severity": "ERROR"}
  {"message": "[Vale.Terms] Use 'Skopeo' instead of 'skopeo'.", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 609, "column": 70}}}, "severity": "ERROR"}
  {"message": "[Vale.Spelling] Did you really mean 'Keyprovider'?", "location": {"path": "content/en/blog/2024/coco-without-confidential-hardware.md", "range": {"start": {"line": 650, "column": 88}}}, "severity": "ERROR"}
```

**Comment by wainersm** [comment]
Linter is happy again! \o/

**Review by fitzthum — APPROVED** [review]
Looks great. Incredible post. We can move some of this stuff into the docs over time as well.

**Review by bpradipt — APPROVED** [review]
/lgtm
Nice @wainersm

**Pull request merged**
