### PR TITLE
ci: add prose linting with vale

### PR DESCRIPTION
**Pull request by mkulke**
This is useful to smoothen the review of submissions and the overall quality of the content.

Vale is able to use certain comprehensive style guides (e.g. Redhat, Microsoft, Google). This PR just uses merely the base check, which already produces some good findings.

We can decide on a more opinionated style guide later.

### CODE REVIEW

**Comment by mkulke** [comment]
@surajssd @ariel-adam are github actions disabled in this repository?

this would be example of a ci [report](https://github.com/mkulke/confidentialcontainers.org/actions/runs/7666993789)

**Review by surajssd — APPROVED** [review]
Thanks Magnus, this is really cool.

**Comment by surajssd** [comment]
> @surajssd @ariel-adam are github actions disabled in this repository?

No, I haven't disabled anything explicitly. I believe this run will only happen once this PR is merged, isn't it?

**Comment by mkulke** [comment]
> > @surajssd @ariel-adam are github actions disabled in this repository?
> 
> No, I haven't disabled anything explicitly. I believe this run will only happen once this PR is merged, isn't it?

let's see...

**Pull request merged**
